# Copyright © 2024 Brent Tunnicliff <brent@tunnicliff.dev>

name: 'Publish lib'
description: 'Publishes and uploads an archive of the lib'
runs:
  using: "composite"
  steps:
    - name: Publish to local Maven
      shell: bash
      run: ./gradlew publishToMavenLocal
    - name: Upload lib
      uses: actions/upload-artifact@v4
      with:
        name: lib
        path: ~/.m2/repository
        if-no-files-found: error